name: Get Events

on:
  issue_comment:
    types: [created, edited]

jobs:
  get-events:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - env:
          ISSUE_CONTEXT: ${{ toJSON(github.event.issue) }}
        run: echo "$ISSUE_CONTEXT"
      #- uses: actions/checkout@v1
      #  with:
      #    persist-credentials: false
      #- name: Set up Python
      #  uses: actions/setup-python@v1
      #  with:
      #    python-version: 3.9
      #- name: Install Dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install .
      #- name: Run get_events
      #  run: |
      #    echo "call script here"
